export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  dashboard: '/dashboard',
  tasks: '/tasks',
  tasksArchive: '/tasks/archive',
  tasksTrash: '/tasks/trash',
  calendar: '/calendar',
  habits: '/habits',
  goals: '/goals',
  expenses: '/expenses',
  notes: '/notes',
  analytics: '/analytics',
  reports: '/reports',
  settings: '/settings',
  settingsProfile: '/settings/profile',
  settingsAppearance: '/settings/appearance',
  settingsPreferences: '/settings/preferences',
  settingsNotifications: '/settings/notifications',
  settingsData: '/settings/data',
} as const
